### ISSUE TITLE
Add-ons Extensions Request

### ISSUE THREAD

**Issue by doitliketyler** [Nutty101/NPC_Destinations3#10]
Hey there. Would be really great if you would make all the add-ons behave like extensions that would work out of the NPC_Destinations folder instead of just the main plugins folder.

**Comment by Nutty101** [comment]
This is part of V3 now. You can drop plugins (if they are designed for it) in your main plugins folder, or inside the destinations plugin folder.  You can also add new plugins without restarting. Working to allow reloading.
